### ISSUE TITLE
Populate_Script has issues with inserting date

### ISSUE THREAD

**Issue by willcgg** [mm1089/advanced-databases-group#3]
When trying to insert the date into the tables using the given format of for example : "11-dec-81" it gives error due to the way SQL Formats dates. SQL formats the above date like so: "11-12-81"

**Comment by ghost** [comment]
Pick 1: SELECT FORMAT (getdate(), 'dddd, MMMM, yyyy') as date
or
SELECT FORMAT (getdate(), 'dd/MM/yyyy ') as date
